### ISSUE TITLE
SIGSEGV when trying the example

### ISSUE THREAD

**Issue by Cybolic** [GaryShearer/QEffects#2]
```
onattachSettings: /home/cybolic/.config/QeffectsGL/QeffectsGL.ini
Module: glxgears.exe
checkinit, 0 0
Loading "libGL.so": I did everything I could...He's dead, Jim.
LD_PRELOAD=./libQeffectsGL_… terminated by signal SIGSEGV (Address boundary error)
```
Someone else seems to have had the same issue a year ago: https://www.reddit.com/r/linux_gaming/comments/30tutf/anyone_know_of_a_way_to_do_postprocessing/cpxay49

**Comment by GaryShearer** [comment]
you can try changing [this](https://github.com/GaryShearer/QEffects/blob/master/qeffects-gl/source/qfx_opengl.cpp#L529) line to your opengl shared object.

**Comment by Cybolic** [comment]
Thanks! That did bring me one step closer. I'm segfaulting on this now though, if you can help
`onattachSettings: /home/cybolic/.config/QeffectsGL/QeffectsGL.ini
Module: glxgears.exe
checkinit, 0 0
Loading "libGL.so": success
Loading functions: success
libGL error: unable to load driver: swrast_dri.so
libGL error: failed to load driver: swrast
X Error of failed request:  BadValue (integer parameter out of range for operation)
  Major opcode of failed request:  154 (GLX)
  Minor opcode of failed request:  3 (X_GLXCreateContext)
  Value in failed request:  0x0
  Serial number of failed request:  35
  Current serial number in output stream:  37`

**Comment by Cybolic** [comment]
Never mind; I still had to use the right library. On my machine, that was /usr/lib/nvidia-367/libGL.so.1.0.0 - thanks for the help!
